import { describe, expect, it } from 'vitest';
import {
  CHECKSUMS_ASSET_NAME,
  MAX_DOWNLOAD_BYTES,
  applyKindFor,
  isRefusal,
  parseChecksums,
  planDownload,
  safeAssetFileName,
  signatureAssetName,
  signerIdentity,
  staleDownloads,
} from './download.js';
import type { Release, ReleaseAsset } from './update.js';

const PREFIX = 'https://github.com/sethcarney/boxwarden/releases/';

function asset(name: string, size = 95_000_000): ReleaseAsset {
  return { name, url: `${PREFIX}download/v1.2.0/${name}`, size };
}

function release(assets: readonly ReleaseAsset[]): Release {
  return {
    version: '1.2.0',
    tag: 'v1.2.0',
    url: `${PREFIX}tag/v1.2.0`,
    assets,
  };
}

/** A release as `.github/workflows/release.yml` actually leaves it. */
function signedRelease(installer: string): Release {
  return release([
    asset(installer),
    asset(signatureAssetName(installer), 6_000),
    asset(CHECKSUMS_ASSET_NAME, 900),
  ]);
}

describe('safeAssetFileName', () => {
  it('accepts every artefact electron-builder emits, spaces included', () => {
    for (const name of [
      'boxwarden-1.2.0.dmg',
      'boxwarden-1.2.0-arm64.dmg',
      'boxwarden-1.2.0.AppImage',
      'boxwarden_1.2.0_amd64.deb',
      'boxwarden Setup 1.2.0.exe',
      'sha256sums.txt',
      'boxwarden-1.2.0.dmg.sigstore.json',
    ]) {
      expect(safeAssetFileName(name)).toBe(name);
    }
  });

  /**
   * The name arrives over the network and becomes a path. Each of these is a
   * separate published technique rather than a variation on one, which is why
   * they are listed rather than summarised.
   */
  it('refuses every way a name can stop being a name', () => {
    for (const name of [
      '../../etc/passwd', // traversal, plainly
      '..\\..\\windows\\system32\\x.exe', // traversal, Windows spelling
      '/etc/passwd', // absolute
      'a/b.dmg', // a separator anywhere at all
      'a\\b.dmg',
      '..',
      '.',
      'x.dmg\u0000.txt', // NUL, which truncates inside a syscall
      'x\u202Eepx.dmg', // right-to-left override: renders as something else
      'x.dmg ', // trailing space, stripped by Windows AFTER validation
      'x.dmg.', // trailing dot, likewise
      ' x.dmg', // leading space
      '-x.dmg', // leading hyphen, which reads as a flag to something
      'x\ny.dmg', // newline, which would forge a line in sha256sums.txt
      '', // nothing
      `${'a'.repeat(200)}.dmg`, // longer than any filesystem wants
    ]) {
      expect(safeAssetFileName(name), name).toBeUndefined();
    }
  });
});

describe('parseChecksums', () => {
  it('reads both spellings sha256sum produces', () => {
    const digests = parseChecksums(
      [
        `${'a'.repeat(64)}  boxwarden-1.2.0.dmg`,
        `${'b'.repeat(64)} *boxwarden Setup 1.2.0.exe`,
      ].join('\n'),
    );

    expect(digests.get('boxwarden-1.2.0.dmg')).toBe('a'.repeat(64));
    expect(digests.get('boxwarden Setup 1.2.0.exe')).toBe('b'.repeat(64));
  });

  it('lower-cases the digest, so a manifest written in either case compares', () => {
    expect(parseChecksums(`${'A'.repeat(64)}  x.dmg`).get('x.dmg')).toBe('a'.repeat(64));
  });

  /**
   * An attacker who can append to the manifest — but not rewrite it — must not
   * be able to override an earlier entry with a later one. First wins.
   */
  it('keeps the first entry when a name appears twice', () => {
    const digests = parseChecksums(
      [`${'a'.repeat(64)}  x.dmg`, `${'b'.repeat(64)}  x.dmg`].join('\n'),
    );
    expect(digests.get('x.dmg')).toBe('a'.repeat(64));
  });

  it('skips lines it cannot read rather than failing the file', () => {
    const digests = parseChecksums(
      [
        '# generated by the release workflow',
        '',
        'not a checksum',
        `${'c'.repeat(64)}  x.dmg`,
      ].join('\n'),
    );
    expect(digests.size).toBe(1);
    expect(digests.get('x.dmg')).toBe('c'.repeat(64));
  });

  it('drops entries whose name would not be written to disk', () => {
    expect(parseChecksums(`${'d'.repeat(64)}  ../../etc/passwd`).size).toBe(0);
  });

  it('refuses a digest that is not exactly 64 hex characters', () => {
    expect(parseChecksums(`${'e'.repeat(63)}  x.dmg`).size).toBe(0);
    expect(parseChecksums(`${'e'.repeat(65)}  x.dmg`).size).toBe(0);
    expect(parseChecksums(`${'z'.repeat(64)}  x.dmg`).size).toBe(0);
  });
});

describe('signerIdentity', () => {
  /**
   * The identity is the entire value of the signature. Any workflow on GitHub
   * can obtain a certificate from the same issuer, so a bundle that merely
   * verifies proves nothing about who produced it.
   */
  it('names this repository, this workflow and this tag', () => {
    expect(signerIdentity('v1.2.0')).toEqual({
      subjectAlternativeName:
        'https://github.com/sethcarney/boxwarden/.github/workflows/release.yml@refs/tags/v1.2.0',
      issuer: 'https://token.actions.githubusercontent.com',
    });
  });

  it('pins the tag, so a signature cannot be replayed onto another version', () => {
    expect(signerIdentity('v1.0.0').subjectAlternativeName).not.toBe(
      signerIdentity('v2.0.0').subjectAlternativeName,
    );
  });
});

describe('planDownload', () => {
  it('resolves the artefact, its signature and the checksum manifest', () => {
    const plan = planDownload(
      signedRelease('boxwarden_1.2.0_amd64.deb'),
      asset('boxwarden_1.2.0_amd64.deb'),
    );

    expect(isRefusal(plan)).toBe(false);
    if (isRefusal(plan)) return;
    expect(plan.fileName).toBe('boxwarden_1.2.0_amd64.deb');
    expect(plan.signature.name).toBe('boxwarden_1.2.0_amd64.deb.sigstore.json');
    expect(plan.checksums.name).toBe('sha256sums.txt');
    expect(plan.identity.subjectAlternativeName).toContain('refs/tags/v1.2.0');
  });

  /**
   * The refusal that matters most. If a missing signature fell back to
   * "checksum only", an attacker who can add an asset to a release would
   * disable the signature check by simply not providing one.
   */
  it('refuses an artefact with no signature beside it', () => {
    const plan = planDownload(
      release([asset('boxwarden-1.2.0.dmg'), asset(CHECKSUMS_ASSET_NAME)]),
      asset('boxwarden-1.2.0.dmg'),
    );

    expect(isRefusal(plan)).toBe(true);
    if (!isRefusal(plan)) return;
    expect(plan.reason).toContain('no signature');
  });

  it('refuses a release with no checksum manifest', () => {
    const plan = planDownload(
      release([asset('boxwarden-1.2.0.dmg'), asset('boxwarden-1.2.0.dmg.sigstore.json')]),
      asset('boxwarden-1.2.0.dmg'),
    );
    expect(isRefusal(plan)).toBe(true);
  });

  it('refuses when no single artefact matched this machine', () => {
    const plan = planDownload(signedRelease('boxwarden-1.2.0.dmg'), undefined);
    expect(isRefusal(plan)).toBe(true);
    if (!isRefusal(plan)) return;
    expect(plan.reason).toContain('could not tell which file');
  });

  it('refuses a name it would not write to disk, rather than sanitising it', () => {
    const hostile = asset('../../evil.dmg');
    const plan = planDownload(
      release([hostile, asset('../../evil.dmg.sigstore.json'), asset(CHECKSUMS_ASSET_NAME)]),
      hostile,
    );
    expect(isRefusal(plan)).toBe(true);
  });

  it('refuses an artefact that declares itself larger than the cap', () => {
    const huge = asset('boxwarden-1.2.0.dmg', MAX_DOWNLOAD_BYTES + 1);
    const plan = planDownload(
      release([huge, asset('boxwarden-1.2.0.dmg.sigstore.json'), asset(CHECKSUMS_ASSET_NAME)]),
      huge,
    );
    expect(isRefusal(plan)).toBe(true);
  });

  /**
   * Asset names come from a workflow, not from a person typing. A
   * case-insensitive match would let `SHA256SUMS.TXT` — an asset anybody with
   * release-edit rights could add — stand in for the real manifest.
   */
  it('matches asset names exactly', () => {
    const plan = planDownload(
      release([
        asset('boxwarden-1.2.0.dmg'),
        asset('boxwarden-1.2.0.dmg.SIGSTORE.json'),
        asset('SHA256SUMS.TXT'),
      ]),
      asset('boxwarden-1.2.0.dmg'),
    );
    expect(isRefusal(plan)).toBe(true);
  });
});

describe('applyKindFor', () => {
  it('replaces only the AppImage, and hands everything else to an installer', () => {
    expect(applyKindFor('appimage')).toBe('replace');
    for (const kind of ['dmg', 'nsis', 'deb', 'linux-unknown', 'unknown'] as const) {
      expect(applyKindFor(kind), kind).toBe('open');
    }
  });
});

describe('staleDownloads', () => {
  const now = new Date('2026-08-10T00:00:00Z');
  const fresh = new Date('2026-08-09T00:00:00Z');
  const old = new Date('2026-07-01T00:00:00Z');

  it('sweeps what nothing is going to install', () => {
    expect(
      staleDownloads(
        [
          { name: 'old.dmg', modifiedAt: old },
          { name: 'recent.dmg', modifiedAt: fresh },
        ],
        undefined,
        now,
      ),
    ).toEqual(['old.dmg']);
  });

  /**
   * Sweeping the file the Install button is offering would delete it out from
   * under the click.
   */
  it('never sweeps the download this run has verified, however old', () => {
    expect(staleDownloads([{ name: 'old.dmg', modifiedAt: old }], 'old.dmg', now)).toEqual([]);
  });

  it('sweeps anything whose name it would not have written, whatever its age', () => {
    expect(staleDownloads([{ name: '..evil', modifiedAt: fresh }], undefined, now)).toEqual([
      '..evil',
    ]);
  });
});
