import fc from 'fast-check';
import { describe, expect, it } from 'vitest';
import { devcontainerName, stripJsonc } from './project.js';

/**
 * Property-based tests for the JSONC scanner.
 *
 * `stripJsonc` reads a file found by walking the user's home directory. It is
 * the one place in this app that parses a document nobody here wrote, and it
 * is a hand-written character scanner rather than a library — which is the
 * right call (see the note in `project.ts`: every `"image"` with a registry
 * host in it contains `//` inside a string, and a regex that does not track
 * string state deletes half the document) and also exactly the kind of code a
 * generator is good at breaking.
 *
 * It broke it, too. The trailing-comma pass used to be a regex over the whole
 * document, which rewrote a `,}` that was two characters of somebody's
 * `"name"` — found by the first property below, fixed by moving that pass into
 * a string-aware scan.
 *
 * Three properties matter, and none of them is "it parses correctly":
 *
 *   - **It never throws, on any input at all.** A scan that dies on one
 *     malformed file loses the other 249 projects it had found. `scan.ts`
 *     catches, but a function that cannot fail is better than a catch that has
 *     to be remembered.
 *   - **It never changes a document that had nothing to strip.** Which is the
 *     `,}`-inside-a-string bug, stated as a rule.
 *   - **It never invents valid JSON.** Stripping comments out of a broken file
 *     must leave it broken. The dangerous direction is a scanner that mangles a
 *     document into something `JSON.parse` accepts and reads a `name` out of
 *     the wreckage.
 */

/** JSON-ish documents with comments in the places a real config has them. */
const jsoncDocument = fc
  .record({
    lead: fc.constantFrom('', '// generated by VS Code\n', '/* multi\n   line */\n'),
    image: fc.constantFrom(
      'mcr.microsoft.com/devcontainers/typescript-node:22',
      'ghcr.io/owner/image:tag',
      'node:22',
    ),
    // Not filtered: a name containing a quote or a backslash is exactly the
    // case the escape tracking exists for, and JSON.stringify puts it in
    // correctly so the document stays valid.
    name: fc.string({ minLength: 1, maxLength: 30 }),
    inner: fc.constantFrom('', '// why this image\n  ', '/* pinned */ '),
    trailingComma: fc.boolean(),
  })
  .map(({ lead, image, name, inner, trailingComma }) => ({
    name,
    image,
    source: `${lead}{
  ${inner}"image": ${JSON.stringify(image)},
  "name": ${JSON.stringify(name)}${trailingComma ? ',' : ''}
}`,
  }));

describe('stripJsonc', () => {
  it('never throws, whatever the file contains', () => {
    fc.assert(
      fc.property(fc.string({ unit: 'binary' }), (source) => {
        expect(() => stripJsonc(source)).not.toThrow();
      }),
    );
  });

  it('preserves length, so JSON.parse error offsets still point at the source', () => {
    // Comments and trailing commas are replaced with spaces rather than
    // removed, which is what makes a parse error's character offset meaningful
    // against the original file. Length equality is the cheap invariant that
    // catches a "tidy-up" rewriting either pass to splice instead of
    // substitute — and it holds unconditionally, with no input excluded.
    fc.assert(
      fc.property(fc.string({ unit: 'binary' }), (source) => {
        expect(stripJsonc(source)).toHaveLength(source.length);
      }),
    );
  });

  it('leaves a document with nothing to strip exactly as it found it', () => {
    // fc.json() emits no comments and no trailing commas — but it does emit
    // strings containing `//` and `,}`, which is the point. Every one of those
    // documents must come back byte-identical.
    fc.assert(
      fc.property(fc.json(), (json) => {
        expect(stripJsonc(json)).toBe(json);
      }),
    );
  });

  it('never turns invalid JSON into valid JSON', () => {
    // The failure that would matter: a scanner that eats a quote and leaves
    // behind something parseable, so a config nobody can read reports a name
    // assembled from the damage.
    //
    // Documents that genuinely contain a comment or a trailing comma are
    // excluded, because turning those into valid JSON is the entire job.
    const notJson = fc
      .string({ unit: 'binary' })
      .filter((s) => {
        try {
          JSON.parse(s);
          return false;
        } catch {
          return true;
        }
      })
      .filter((s) => !s.includes('//') && !s.includes('/*') && !/,\s*[}\]]/.test(s));

    fc.assert(
      fc.property(notJson, (source) => {
        expect(() => JSON.parse(stripJsonc(source)) as unknown).toThrow();
      }),
    );
  });

  it('keeps a `//` that is inside a string while removing the comments', () => {
    // The regression this scanner was written for, as a property: whatever
    // comments the document carries, the image reference survives intact and
    // the result parses.
    fc.assert(
      fc.property(jsoncDocument, ({ image, source }) => {
        const stripped = stripJsonc(source);
        expect(stripped).toContain(image);
        expect(JSON.parse(stripped)).toMatchObject({ image });
      }),
    );
  });
});

describe('devcontainerName', () => {
  it('reads the name back out of a JSONC document that has one', () => {
    fc.assert(
      fc.property(jsoncDocument, ({ name, source }) => {
        const trimmed = name.trim();
        fc.pre(trimmed !== '');
        expect(devcontainerName(source)).toBe(trimmed);
      }),
    );
  });

  it('answers undefined rather than throwing, on any input', () => {
    // Called on every devcontainer.json the walk finds. A project whose config
    // does not parse is still a project the user wants to open — very likely
    // in order to fix exactly that.
    fc.assert(
      fc.property(fc.string({ unit: 'binary' }), (source) => {
        const result = devcontainerName(source);
        expect(result === undefined || typeof result === 'string').toBe(true);
      }),
    );
  });
});
